spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/visitor_service
    username: postgres
    password: 2305
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: visitor_service